#  docker compose down -v && docker compose up
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - pgdataKC:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - custom
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_LOG_LEVEL: "knemognition.heartauth.authenticators:info"
    command: >
      start-dev --http-enabled=true --http-port=8080 --import-realm
    ports: ["9000:8080"]
    volumes:
      - ./authenticators/target:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./realms:/opt/keycloak/data/import
    networks:
      - poziomk3
      - custom
volumes:
  pgdataKC:
networks:
  poziomk3: 
    external: true
  custom:
    driver: bridge
